apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: invoker
spec:
  template:
    spec:
      containers:
      - image: github.com/n3wscott/task/cmd/ceinvoker
        env:
        - name: TARGET
          value: http://default-broker.default.svc.cluster.local
